FROM alpine:3.23
ARG TARGETOS
ARG TARGETARCH

RUN apk add --no-cache wireguard-tools nftables iproute2 ca-certificates

COPY linux/${TARGETARCH}/wg-manager /usr/local/bin/wg-manager
RUN chmod +x /usr/local/bin/wg-manager

WORKDIR /app
COPY web /app/web

EXPOSE 8080/tcp
EXPOSE 51820/udp
ENTRYPOINT ["/usr/local/bin/wg-manager"]
